class CreateVersionTables < ActiveRecord::Migration

  def self.up_worker(table)
    add_column(table.to_sym, :creator_id, :integer)
    add_column(table.to_sym, :updater_id, :integer)
    add_column(table.to_sym, :deleted_at, :timestamp)
    table.singularize.camelize.constantize.create_versioned_table
    execute "update #{table} set lock_version=1 where lock_version is null"
  end

  def self.up
    up_worker('absolute_pitch_survey_family_histories')
    up_worker('allergies')
    up_worker('allergy_descriptions')
    up_worker('answer_options')
    up_worker('baseline_traits_surveys')
    up_worker('ccrs')
    up_worker('condition_descriptions')
    up_worker('conditions')
    up_worker('content_areas')
    up_worker('demographics')
    up_worker('distinctive_traits')
    up_worker('documents')
    up_worker('enrollment_step_completions')
    up_worker('enrollment_steps')
    up_worker('family_relations')
    up_worker('family_survey_responses')
    up_worker('genetic_data')
    up_worker('immunization_names')
    up_worker('immunizations')
    up_worker('informed_consent_responses')
    up_worker('international_participants')
    up_worker('invited_emails')
    up_worker('kit_designs')
    up_worker('lab_test_result_descriptions')
    up_worker('lab_test_results')
    up_worker('mailing_list_subscriptions')
    up_worker('mailing_lists')
    up_worker('medication_names')
    up_worker('medications')
    up_worker('named_proxies')
    up_worker('privacy_survey_responses')
    up_worker('procedure_descriptions')
    up_worker('procedures')
    up_worker('question_responses')
    up_worker('residency_survey_responses')
    up_worker('safety_questionnaires')
    up_worker('screening_survey_responses')
    up_worker('studies')
    up_worker('survey_answer_choices')
    up_worker('survey_answers')
    up_worker('survey_questions')
    up_worker('survey_sections')
    up_worker('surveys')
    up_worker('user_logs')
    up_worker('users')
    up_worker('waitlists')
  end

  def self.down_worker(table)
    table.singularize.camelize.constantize.drop_versioned_table
    remove_column(table.to_sym, :creator_id)
    remove_column(table.to_sym, :updater_id)
    remove_column(table.to_sym, :deleted_at)
  end

  def self.down
    down_worker('absolute_pitch_survey_family_histories')
    down_worker('allergies')
    down_worker('allergy_descriptions')
    down_worker('answer_options')
    down_worker('baseline_traits_surveys')
    down_worker('ccrs')
    down_worker('condition_descriptions')
    down_worker('conditions')
    down_worker('content_areas')
    down_worker('demographics')
    down_worker('distinctive_traits')
    down_worker('documents')
    down_worker('enrollment_step_completions')
    down_worker('enrollment_steps')
    down_worker('family_relations')
    down_worker('family_survey_responses')
    down_worker('genetic_data')
    down_worker('immunization_names')
    down_worker('immunizations')
    down_worker('informed_consent_responses')
    down_worker('international_participants')
    down_worker('invited_emails')
    down_worker('kit_designs')
    down_worker('lab_test_result_descriptions')
    down_worker('lab_test_results')
    down_worker('mailing_list_subscriptions')
    down_worker('mailing_lists')
    down_worker('medication_names')
    down_worker('medications')
    down_worker('named_proxies')
    down_worker('privacy_survey_responses')
    down_worker('procedure_descriptions')
    down_worker('procedures')
    down_worker('question_responses')
    down_worker('residency_survey_responses')
    down_worker('safety_questionnaires')
    down_worker('screening_survey_responses')
    down_worker('studies')
    down_worker('survey_answer_choices')
    down_worker('survey_answers')
    down_worker('survey_questions')
    down_worker('survey_sections')
    down_worker('surveys')
    down_worker('user_logs')
    down_worker('users')
    down_worker('waitlists')
  end
end

